#!/bin/bash
datenow=$(date +%s)
echo -e "\E[44;1;37m User          Date         State         Action   \E[0m"
echo ""
for user in $(awk -F: '{print $1}' /etc/passwd); do
	expdate=$(chage -l $user|awk -F: '/Account expires/{print $2}')
	echo $expdate|grep -q never && continue
	datanormal=$(date -d"$expdate" '+%d/%m/%Y')
	tput setaf 3 ; tput bold ; printf '%-15s%-17s%s' $user $datanormal ; tput sgr0
	expsec=$(date +%s --date="$expdate")
	diff=$(echo $datenow - $expsec|bc -l)
	tput setaf 2 ; tput bold
	echo $diff|grep -q ^\- && echo "VALID   NOT REMOVED" && continue
	tput setaf 1 ; tput bold
	echo "EXPIRED   WAS REMOVED"
	pkill -f $user
	userdel --force $user
	grep -v ^$user[[:space:]] /root/users.db > /tmp/ph ; cat /tmp/ph > /root/users.db
done
echo '0' > /etc/SSHPlus/Exp
tput sgr0 
echo ""